stages:
  convert_labeled_data:
    cmd: python src/convert_labeled_data.py
    deps:
    - data/labeled_data.csv
    - src/convert_labeled_data.py
    outs:
    - data/annotation_per_row_data.csv
  fetch_labeled_data:
    cmd: ./src/fetch_data.sh
    deps:
    - src/fetch_data.sh
    outs:
    - data/labeled_data.csv
  download_audio:
    cmd: python ./src/download_audio.py --target-dir data/audio --annotations-file
      data/annotation_per_row_data.csv
    deps:
    - data/annotation_per_row_data.csv
    - src/download_audio.py
    outs:
    - data/audio:
        persist: true
  extract_data_quality:
    cmd: python ./src/extract_data_quality.py
    deps:
    - data/annotation_per_row_data.csv
    - src/extract_data_quality.py
    outs:
    - data/data_quality/sample_based_quality.json
    - data/data_quality/samples_per_label.csv
  fetch_noise_esc50:
    cmd: python src/fetch_noise_esc50.py
    deps:
    - src/fetch_noise_esc50.py
    - src/noise_pool.py
    params:
    - noise_pools.esc50
    outs:
    - data/noise/esc50

  fetch_noise_demand:
    cmd: python src/fetch_noise_demand.py
    deps:
    - src/fetch_noise_demand.py
    - src/noise_pool.py
    params:
    - noise_pools.demand
    outs:
    - data/noise/demand

  augmentation:
    cmd: python src/augment_data.py
    deps:
    - data/audio
    - data/noise/esc50
    - data/noise/demand
    - data/annotation_per_row_data.csv
    - src/augment_data.py
    params:
    - chunk_size
    - chunk_overlap
    - augmentation
    outs:
    - data/augmented_audio
    - data/augmented_annotations.csv

  extract_features:
    cmd: python src/extract_mfcc_features.py
    deps:
    - data/audio
    - data/augmented_audio
    - data/noise/esc50
    - data/noise/demand
    - src/extract_mfcc_features.py
    params:
    - feature_extraction
    - augmentation.external_noise_pools
    outs:
    - data/mfcc_data/

  draw_data:
    cmd: python src/draw_data.py
    params:
    - inbalance_ratio
    - external_background_ratio
    - chunk_size
    - chunk_overlap
    - augmentation.external_noise_pools
    deps:
    - data/annotation_per_row_data.csv
    - data/augmented_annotations.csv
    - data/mfcc_data/
    - data/noise/esc50
    - data/noise/demand
    - src/draw_data.py
    outs:
    - data/balanced_data.h5
    - data/data_quality/chunk_balanced_quality.json
    - data/data_quality/chunks_per_label.csv

  train_model:
    cmd: python src/train_xgboost.py
    deps:
    - data/balanced_data.h5
    - data/data_quality/sample_based_quality.json
    - data/data_quality/samples_per_label.csv
    - data/data_quality/chunk_balanced_quality.json
    - data/data_quality/chunks_per_label.csv
    - src/train_xgboost.py
    params:
    - model
    - training
    outs:
    - models/xgboost_model.json

metrics:
- data/data_quality/sample_based_quality.json
- data/data_quality/chunk_balanced_quality.json
plots:
- number of samples vs label:
    template: bar_horizontal_sorted
    x: '0'
    y:
      data/data_quality/samples_per_label.csv: label
params:
- params.yaml
