"""Pure TFLite helpers shared by the quantize and evaluate stages.

No params, no I/O of its own -- quantize_model.py builds and converts,
evaluate_quantized.py scores. Keeping the conversion and the scoring in one
place is what makes the two stages agree on what "the exported graph" is.
"""

from pathlib import Path

import numpy as np
import tensorflow as tf
from tensorflow import keras

C_ARRAY_VAR = "g_doorbell_model_data"


def build_export_model(trained: keras.Model, mean: np.ndarray, std: np.ndarray):
    """Prepend per-bin normalization so the graph consumes raw log-mel.

    mean/std come from normalization_stats() with shape (n_bins, 1, 1), which
    broadcasts over the (batch, n_bins, n_frames, 1) input.
    """
    inputs = keras.Input(shape=trained.input_shape[1:], name="logmel")
    x = keras.layers.Rescaling(
        scale=(1.0 / std).astype(np.float32),
        offset=(-mean / std).astype(np.float32),
        name="normalize",
    )(inputs)
    outputs = trained(x)
    return keras.Model(inputs, outputs, name="doorbell_int8_export")


def convert_int8(model: keras.Model, representative: np.ndarray) -> bytes:
    """Full-integer PTQ. int8 in and out so no float ops remain for TFLM."""
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8

    def representative_dataset():
        for sample in representative:
            yield [sample[np.newaxis, ...].astype(np.float32)]

    converter.representative_dataset = representative_dataset
    return converter.convert()


def tflite_predict(tflite_model: bytes, X: np.ndarray) -> np.ndarray:
    """Run the int8 interpreter sample by sample, returning float scores."""
    interpreter = tf.lite.Interpreter(model_content=tflite_model)
    interpreter.allocate_tensors()
    inp = interpreter.get_input_details()[0]
    out = interpreter.get_output_details()[0]

    in_scale, in_zero = inp["quantization"]
    out_scale, out_zero = out["quantization"]

    scores = np.empty(len(X), dtype=np.float32)
    for i, sample in enumerate(X):
        quantized = np.clip(
            np.round(sample / in_scale + in_zero), -128, 127
        ).astype(np.int8)
        interpreter.set_tensor(inp["index"], quantized[np.newaxis, ...])
        interpreter.invoke()
        raw = interpreter.get_tensor(out["index"])[0, 0]
        scores[i] = (float(raw) - out_zero) * out_scale
    return scores


def largest_activation_bytes(tflite_model: bytes) -> int:
    """Biggest intermediate tensor, as an int8 arena sanity check.

    Not the arena size itself -- TFLM's real requirement depends on its
    allocation planner and has to be confirmed on device -- but this is the
    number that decides internal SRAM vs PSRAM.
    """
    interpreter = tf.lite.Interpreter(model_content=tflite_model)
    interpreter.allocate_tensors()
    return max(
        int(np.prod(d["shape"])) * np.dtype(d["dtype"]).itemsize
        for d in interpreter.get_tensor_details()
        if len(d["shape"]) > 0
    )


def write_c_array(data: bytes, path: Path, var_name: str) -> None:
    """Emit an xxd-style C array plus its header, for the firmware build.

    The array is 16-byte aligned because TFLM requires the flatbuffer to be
    aligned before it will parse it in place.
    """
    lines = [
        "// Generated by src/export_tflite.py -- do not edit.",
        "//",
        f"// int8 doorbell classifier, {len(data)} bytes.",
        "",
        f'#include "{path.with_suffix(".h").name}"',
        "",
        f"alignas(16) const unsigned char {var_name}[] = {{",
    ]
    for offset in range(0, len(data), 12):
        chunk = ", ".join(f"0x{byte:02x}" for byte in data[offset : offset + 12])
        lines.append(f"    {chunk},")
    lines.append("};")
    lines.append(f"const unsigned int {var_name}_len = {len(data)};")
    lines.append("")
    path.write_text("\n".join(lines))

    guard = path.with_suffix(".h").name.upper().replace(".", "_") + "_"
    path.with_suffix(".h").write_text(
        "\n".join(
            [
                "// Generated by src/export_tflite.py -- do not edit.",
                "",
                f"#ifndef {guard}",
                f"#define {guard}",
                "",
                f"extern const unsigned char {var_name}[];",
                f"extern const unsigned int {var_name}_len;",
                "",
                f"#endif  // {guard}",
                "",
            ]
        )
    )
